import Link from "next/link";
import { ComponentLinksButton, ComponentLinksLink } from "../../model/autogenerated-graphql-strapi";


interface CustomLinkProps {
  link: ComponentLinksButton | ComponentLinksLink,
  children: React.ReactNode[] | React.ReactNode
};

const CustomLink = ({ link, children } : CustomLinkProps) => {
  const isInternalLink = link.url?.startsWith('/')

  // For internal links, use the Next.js Link component
  if (isInternalLink) {
    return (
      <Link href="/strapi/[[...slug]]" as={link.url!}>
        <a>
          {children}
        </a>
      </Link>
    )
  }

  // Plain <a> tags for external links
  return (
    <a
      href={link.url!}
      // Change target and rel attributes is newTab is turned on
      target={link.newTab ? "_blank" : "_self"}
      rel={`noreferrer ${link.newTab ? "noopener" : ""}`}
    >
      {children}
    </a>
  );  
}

export default CustomLink;
