import PropTypes from "prop-types";
import { ComponentSectionsRichText } from "../../model/autogenerated-graphql-strapi";

interface RichTextProps {
  data: ComponentSectionsRichText
}

const RichText:React.FC<RichTextProps> = ({ data }:RichTextProps) => {
  return (
    <div className="prose prose-lg container py-12">
      {data.content}
    </div>
  );
};

export default RichText;
