import React from "react";
import { ComponentArchitectureArchitectureModuleFeature } from "../../model/autogenerated-graphql-strapi";
import { CodeSnippet } from "../code-snippet/code-snippet";


//------------------ TYPES
interface ArchitectureModuleFeatureProps {
  feature: ComponentArchitectureArchitectureModuleFeature;
  firstItem: boolean;
}


//------------------ COMPONENT
export const ArchitectureModuleFeature : React.FC<ArchitectureModuleFeatureProps> = (props:ArchitectureModuleFeatureProps) => {
  
  //----- render
  return (
    <div className={props.firstItem?"mt-3":"mt-5"}>
      <h4 className="text-brand1">{props.feature.title}</h4>
      {props.feature.description && props.feature.description !== "" && (<>{props.feature.description}<br/></>)}
      {props.feature.codeSnippet && props.feature.codeSnippet.length > 0 && (
        <>
          {props.feature.codeSnippet.map((codeSnippet)=>{
            return <CodeSnippet codeSnippet={codeSnippet!} key={codeSnippet!.id} />
          })}
        </>        
      )}
    </div>
  );
}