import React from "react";
import { ComponentArchitectureArchitectureModuleFeature } from "../../model/autogenerated-graphql-strapi";
import sanitizeHtml from 'sanitize-html';
import { mySanitizeHtml } from "../../helper/generic-helper";
import dynamic from "next/dynamic";

const CodeSnippet = dynamic(() => import('../code-snippet/code-snippet'));
const MDBCollapse:any = dynamic(() => import('mdbreact').then((mod:any) => mod.MDBCollapse));
const MDBIcon:any = dynamic(() => import('mdbreact').then((mod:any) => mod.MDBIcon));


//------------------ TYPES
interface ArchitectureModuleFeatureProps {
  feature: ComponentArchitectureArchitectureModuleFeature;
  firstItem: boolean;
  onAccordionClick: (id:string)=>void;
  isOpen: boolean;
}


//------------------ COMPONENT
const ArchitectureModuleFeature : React.FC<ArchitectureModuleFeatureProps> = (props:ArchitectureModuleFeatureProps) => {
  
  //----- render
  return (
    <div className={props.firstItem?"mt-3":"mt-5"}>
      <h4 className={`${props.isOpen?"text-brand1":""} clickable`} onClick={()=>props.onAccordionClick(props.feature.id)}>{props.feature.title} <MDBIcon icon={`fas ${props.isOpen?"fa-angle-down":"fa-angle-right"}`} /></h4>
      <MDBCollapse id={props.feature.id} isOpen={props.isOpen}>
        {props.feature.description && props.feature.description !== "" && (<div dangerouslySetInnerHTML={{__html: mySanitizeHtml(sanitizeHtml, sanitizeHtml.defaults, props.feature.description)}} />)}
        {props.feature.codeSnippet && props.feature.codeSnippet.length > 0 && (
          <>
            {props.feature.codeSnippet.map((codeSnippet)=>{
              return <CodeSnippet codeSnippet={codeSnippet!} key={codeSnippet!.id} />
            })}
          </>        
      )}
      </MDBCollapse>
    </div>
  );
}

export default ArchitectureModuleFeature;