import React from "react";
import { ComponentArchitectureArchitectureModuleFeature } from "../../model/autogenerated-graphql-strapi";
import { CodeSnippet } from "../code-snippet/code-snippet";
import styles from "./architecture-module-feature.module.scss";

//------------------ TYPES
interface ArchitectureModuleFeatureProps {
  feature: ComponentArchitectureArchitectureModuleFeature;
}


//------------------ COMPONENT
export const ArchitectureModuleFeature : React.FC<ArchitectureModuleFeatureProps> = (props:ArchitectureModuleFeatureProps) => {
  
  //----- render
  return (
    <div>
      <h4>{props.feature.title}</h4>
      Description: {props.feature.description}<br/>
      {props.feature.codeSnippet && props.feature.codeSnippet.length > 0 && (
        <>
          <div>Code snippets: <br/></div>
          {props.feature.codeSnippet.map((codeSnippet)=>{
            return <CodeSnippet codeSnippet={codeSnippet!} key={codeSnippet!.id} />
          })}
        </>        
      )}
    </div>
  );
}