import {Query as StrapiQuery} from "../model/autogenerated-graphql-strapi";

export interface ErrorResponse {
  statusCode: number;
  message: string;
}

export interface ErrorException {
  message: string;
}

export interface ErrorExtension {
  code: string;
  serviceName: string;
  response: ErrorResponse;
  exception: ErrorException;
}

export interface Error {
  message?: string;
  extensions: ErrorExtension;
}

// -------- BASE RESPONSE
export interface BaseResponse<T> {
  data?: Query<T>;
  errors: Error[];
}

export interface StrapiResponse {
  data?: StrapiQuery;
}

// -------- QUERY
export interface Query<T> {
  experiences?: T;
  randomQuotes?: T;
  experienceGraph?: T;
  login: T;
}

// -------- BATTISTI LOGIN
export interface BattistiLogin {
  accessToken: string;
}

// -------- QUOTE
export interface Quote {
  content: string;
  author: string;
  image?: string;
}


// --------  TASK
export interface Task {
  id: string
}


// --------  COMPANY
export interface Company {
  name: string,
  from: string,
  to?: string,
  city: string,
  country: string,
  logoFilename: string
}


// --------  CUSTOMER
export interface Customer {
  id: string,
  name: string,
  logoFilename: string
}


// --------  SECTOR
export interface Sector {
  id: string
}


// --------  SKILL
export interface Skill {
  name: string,
  usagePercentage: number
}


// --------  EXPERIENCE
export interface Experience {
  id: string,
  from: string,
  to?: string,
  avatarFilename: string,
  tasks: Task[],
  companies: Company[],
  customers: Customer[],
  sectors: Sector[],
  skills: Skill[]
}


// --------  FORCE GRAPH
export namespace ForceGraph {
  
  export interface Node {
    id: string,
    name: string,
    val: number,
    group: number
  }

  export interface Link {
    source: string,
    target: string
  }

  export interface Graph {
    nodes: Node[],
    links: Link[]
  }
}

// --------  COOKIEBOT CookieConsent
export interface CookieConsent {
  stamp: string,
  necessary: boolean,
  preferences: boolean,
  statistics: boolean,
  marketing: boolean,
  ver: number,
  utc: number,
  region: string
}
