
/*
# Strapi Demo

This code has been migrated from https://github.com/strapi/strapi-starter-next-corporate only for demo purpose.
*/

import { ComponentLinksLink } from "./autogenerated-graphql-strapi";


// export interface StrapiLink {
//   id: string | number,
//   url: string,
//   text: string,
//   newTab: boolean
// };

// export interface StrapiMedia{
//   id: string | number,
//   alternativeText: string,
//   mime: string,
//   url: string
// };

// export interface StrapiButtonLink extends ComponentLinksLink{
//   theme: string,
//   type: string
// };
