import { ComponentArchitectureCodeSnippet } from "../../model/autogenerated-graphql-strapi";
import styles from "./code-snippet.module.scss";

//------------------ TYPES
interface CodeSnippetProps {
  codeSnippet: ComponentArchitectureCodeSnippet;
}


//------------------ COMPONENT
export const CodeSnippet : React.FC<CodeSnippetProps> = (props:CodeSnippetProps) => {
  
  //----- render
  return (
    <div>
      File path: {props.codeSnippet.filePath}<br/>
      Description: {props.codeSnippet.description}<br/>
      Code: {props.codeSnippet.code}<br/>
      Language: {props.codeSnippet.language}<br/>
    </div>
  );
}