import React, { useState, useRef, RefObject, useEffect } from 'react';
import { ReactSVG } from 'react-svg'
import styles from "./architecture.module.scss";
import { TransformWrapper, TransformComponent } from "react-zoom-pan-pinch";
import { MDBIcon } from 'mdbreact';
import { FormattedMessage } from 'react-intl';
import { MDBCard } from 'mdbreact';
import { MDBCardBody } from 'mdbreact';
import { FloatingMenu, MainButton, ChildButton } from 'react-floating-button-menu';
import { ArchitectureChalkboardToolbar } from './architecture-chalkboard-toolbar';
import { ArchitectureType } from '../../pages/kealab';
import { PAGE_ROOT_ID } from '../../core/route.constants';
import { scrollToSection as scrollToSectionHelper, isClient, disableScrollIntoView } from '../../helper/generic-helper';
import { useRouter } from 'next/router';
import { connect } from 'react-redux';
import { IStoreState } from '../../core/store/store.type';
import { ArchitectureModule } from '../../model/autogenerated-graphql-strapi';
import { getStrapiMedia } from '../../helper/strapi-helper';
import sanitizeHtml from 'sanitize-html';


//------------------ TYPES
interface ArchitectureProps {
  architectureType: ArchitectureType;
  onArchitectureTypeSelection: (architectureType: ArchitectureType)=>void;
  modules: ArchitectureModule[];
  chalkboard: string;
  previousUrl?: string;
}

export interface ArchitectureImplProps{
  modules: ArchitectureModule[];
  onArchitectureTypeSelection: (architectureType: ArchitectureType)=>void;
}


//------------------ COMPONENT
const Architecture : React.FunctionComponent<ArchitectureProps> = (props) => {
  
  const router = useRouter();
  const [isOpen, setIsOpen] = useState(false);
  const [currentUrl, setCurrentUrl] = useState("");

  const moduleDetailsRef:RefObject<HTMLDivElement> = useRef(null)
  const moduleDescriptionRef:RefObject<HTMLDivElement> = useRef(null);
  const moduleFeaturesRef:RefObject<HTMLDivElement> = useRef(null);
  const moduleRoadmapRef:RefObject<HTMLDivElement> = useRef(null);


  //----- useEffect
  useEffect(() => {
    setCurrentUrl(location.href);
  });


  //----- afterInjection
  function afterInjection(error:Error|null, svg:SVGElement|undefined):void{
    if (svg && props.modules){
      disableScrollIntoView(props.modules.map((module)=>{return module.moduleId}), null);
      props.modules.forEach((module)=>{
        let svgElem = svg.querySelector("#"+module.moduleId);
        if (svgElem){
          svgElem.classList.add(styles["architecture__module"]);
          svgElem.addEventListener("click", ()=>{
            navigateToModule(module.moduleId);
            setCurrentUrl(router.asPath+"#"+module.moduleId);
            scrollToSection(moduleDetailsRef, PAGE_ROOT_ID);
          });
        }
      })
    }
  }


  //----- scrollToSection
  function scrollToSection(ref:RefObject<HTMLDivElement>, parentId:string):void{
    scrollToSectionHelper(ref, parentId);
    setIsOpen(false);
  }


  //----- navigateToModule
  function navigateToModule(moduleId:string):void{
    router!.push("#"+moduleId);
  }


  //----- render
  // console.log("render " + currentUrl);
  return (
    <div>
      <div className="w-100 text-center">
        <div className={`${styles["architecture__chalkboard-container"]}`}>
          <TransformWrapper defaultScale={1}>
            {(zoomPanPinchProps:any) => (
              <React.Fragment>
                <ArchitectureChalkboardToolbar modules={props.modules} moduleDetailsRef={moduleDetailsRef} onArchitectureTypeSelection={props.onArchitectureTypeSelection} navigateToModule={navigateToModule} architectureType={props.architectureType} zoomPanPinchProps={zoomPanPinchProps} />
                <TransformComponent>
                  <ReactSVG src={props.chalkboard} renumerateIRIElements={false} afterInjection={afterInjection} className={styles["architecture__chalkboard"]}/>
                </TransformComponent>
              </React.Fragment>
            )}
          </TransformWrapper>
        </div>
      </div>

      <div id="module-details" ref={moduleDetailsRef}>
        {
          props.modules.map(module => {
            return (
              (currentUrl.indexOf("#"+module.moduleId) != -1)&&<div key={module.moduleId} data-modulename={module.moduleId} className={(currentUrl.indexOf("#"+module.moduleId) == -1)?"d-none":""}>
                <div className="mt-6 mb-4 w-100 text-center"><img className={`${styles["architecture__module-logo"]}`} src={getStrapiMedia(module.logo?.url)!} /></div>
                <MDBCard className="h-100 w-100 mt-5">
                  <MDBCardBody className={`h-100 ${styles["experience__card-body-chart"]} pt-5 pl-4 pl-md-5 pr-4 pr-md-5`}>
                    <div className={`${styles["architecture__module-details-toolbar"]} ${styles["architecture__speed-dial"]}`}>
                      <FloatingMenu
                        slideSpeed={500}
                        direction="down"
                        spacing={8}
                        isOpen={isOpen} >
                        <MainButton
                          iconResting={<MDBIcon icon="list-ul" />}
                          iconActive={<MDBIcon icon="list-ul" />}
                          onClick={() => setIsOpen(!isOpen)}
                          size={56} />
                        <ChildButton
                          icon={<FormattedMessage id="KEALAB.MODULE_DETAILS.MENU.DESCRIPTION" />}
                          size={40}
                          onClick={()=>{ scrollToSection(moduleDescriptionRef, PAGE_ROOT_ID);}} />
                        <ChildButton
                          icon={<FormattedMessage id="KEALAB.MODULE_DETAILS.MENU.FEATURES" />}
                          size={40} 
                          onClick={()=>{ scrollToSection(moduleFeaturesRef, PAGE_ROOT_ID); }} />
                        <ChildButton
                          icon={<FormattedMessage id="KEALAB.MODULE_DETAILS.MENU.ROADMAP" />}
                          size={40}
                          onClick={()=>{ scrollToSection(moduleRoadmapRef, PAGE_ROOT_ID); }} />
                        <ChildButton
                          icon={<MDBIcon fab icon="github"/>}
                          size={40}
                          onClick={()=>{setIsOpen(false); window.open("https://github.com/keadex/"+module.moduleId, "_blank"); }} />
                      </FloatingMenu>
                    </div>
                    <div ref={moduleDescriptionRef} id="module-description">
                      <h1><FormattedMessage id="KEALAB.MODULE_DETAILS.MENU.DESCRIPTION" /></h1>
                      <div dangerouslySetInnerHTML={{__html: sanitizeHtml(module.description)}} />
                    </div>
                    <div className="mt-5" ref={moduleFeaturesRef} id="module-features">
                      <h1><FormattedMessage id="KEALAB.MODULE_DETAILS.MENU.FEATURES" /></h1>
                      <div dangerouslySetInnerHTML={{__html: sanitizeHtml(module.features)}} />
                    </div>
                    <div className="mt-5" ref={moduleRoadmapRef} id="module-roadmap">
                      <h1><FormattedMessage id="KEALAB.MODULE_DETAILS.MENU.ROADMAP" /></h1>
                      <div dangerouslySetInnerHTML={{__html: sanitizeHtml(module.roadmap)}} />
                    </div>
                  </MDBCardBody>
                </MDBCard>
              </div>     
            )           
          })
        }          
      </div>
    </div>
  );
}

const mapStateToProps = (state:IStoreState) => {
  return {
    previousUrl: state.app.previousUrl
  }
}

export default connect(
  mapStateToProps,
  null
)(Architecture)