import React from 'react';
import Architecture, {ArchitectureImplProps } from './architecture';
import { ArchitectureType } from '../../pages/kealab';
import { useIntl } from 'react-intl';
import InfrArchSvg from '../../../public/img/infrastructure-architecture.svg'; 
import { ArchitectureModule } from '../../model/autogenerated-graphql-strapi';


//------------------ TYPES


//------------------ COMPONENT
export const InfrastructureArchitecture : React.FunctionComponent<ArchitectureImplProps> = (props:ArchitectureImplProps) => {
  
  const intl = useIntl();

  //----- render
  return (
    <React.Fragment>
      <Architecture 
        architectureType={ArchitectureType.infrastructure} 
        onArchitectureTypeSelection={props.onArchitectureTypeSelection}
        modules={props.modules}
        chalkboard={InfrArchSvg} />
    </React.Fragment>
  );
}